const vocabList = [
  {
    word: "negotiate",
    meaning: "to discuss terms to reach an agreement",
    examples: [
      "The sales manager negotiated a better contract with the supplier.",
      "We need to negotiate delivery dates before signing the deal.",
    ],
  },
  {
    word: "deadline",
    meaning: "the latest time by which something must be done",
    examples: [
      "Please submit your expense report before the Friday deadline.",
      "Missing the project deadline can delay product launch.",
    ],
  },
  {
    word: "allocate",
    meaning: "to distribute resources for a specific purpose",
    examples: [
      "The director allocated more budget to digital marketing.",
      "We should allocate extra staff during the busy season.",
    ],
  },
  {
    word: "revenue",
    meaning: "income generated by business operations",
    examples: [
      "Quarterly revenue increased by 12 percent this year.",
      "Higher subscription sales improved our recurring revenue.",
    ],
  },
  {
    word: "efficient",
    meaning: "working well without wasting time or resources",
    examples: [
      "The new filing system made our office more efficient.",
      "An efficient workflow helps teams meet tight schedules.",
    ],
  },
];

let current = 0;
let learned = [];
let email = "";

const emailInput = document.getElementById("email");
const startBtn = document.getElementById("startBtn");
const flashcardSection = document.getElementById("flashcardSection");
const doneSection = document.getElementById("doneSection");
const wordEl = document.getElementById("word");
const meaningEl = document.getElementById("meaning");
const examplesEl = document.getElementById("examples");
const revealBtn = document.getElementById("revealBtn");
const backSide = document.getElementById("backSide");
const learnedBtn = document.getElementById("learnedBtn");
const skipBtn = document.getElementById("skipBtn");
const progressEl = document.getElementById("progress");
const sendMailBtn = document.getElementById("sendMailBtn");
const mailStatus = document.getElementById("mailStatus");

function renderCard() {
  const item = vocabList[current];
  wordEl.textContent = item.word;
  meaningEl.textContent = item.meaning;
  examplesEl.innerHTML = "";

  item.examples.forEach((sentence) => {
    const li = document.createElement("li");
    li.textContent = sentence;
    examplesEl.appendChild(li);
  });

  backSide.classList.add("hidden");
  progressEl.textContent = `Card ${current + 1} of ${vocabList.length} | Learned: ${learned.length}`;
}

function goNext() {
  current += 1;
  if (current >= vocabList.length) {
    flashcardSection.classList.add("hidden");
    doneSection.classList.remove("hidden");
    return;
  }
  renderCard();
}

startBtn.addEventListener("click", () => {
  const value = emailInput.value.trim();
  if (!value) {
    alert("Please enter your email first.");
    return;
  }

  email = value;
  current = 0;
  learned = [];

  document.querySelector(".setup").classList.add("hidden");
  flashcardSection.classList.remove("hidden");
  renderCard();
});

revealBtn.addEventListener("click", () => {
  backSide.classList.remove("hidden");
});

learnedBtn.addEventListener("click", () => {
  const item = vocabList[current];
  if (!learned.some((v) => v.word === item.word)) {
    learned.push(item);
  }
  goNext();
});

skipBtn.addEventListener("click", goNext);

sendMailBtn.addEventListener("click", () => {
  const today = new Date().toISOString().split("T")[0];

  if (learned.length === 0) {
    mailStatus.textContent = "No learned words to send today.";
    return;
  }

  const subject = encodeURIComponent(`TOEIC words learned on ${today}`);
  const bodyText = learned
    .map((item, idx) => `${idx + 1}. ${item.word} — ${item.meaning}`)
    .join("%0D%0A");

  const body = encodeURIComponent(`Here are my learned TOEIC words today:\n\n${decodeURIComponent(bodyText)}`);
  const mailtoUrl = `mailto:${email}?subject=${subject}&body=${body}`;

  window.location.href = mailtoUrl;
  mailStatus.textContent = "Your mail app has been opened with today's learned words.";
});
